- hosts: all 
  tasks:
    - name: test
      copy:
        src: ./var/config
        dest: /root/config
    - name: test_log
      command:
        cmd: ip a
      register: output
    - name: xuat ra man hinh
      debug: var=output.stdout_lines
    - name: host_name
      local_action: "copy content='{{ output.stdout_lines }}' dest=./var/{{ ansible_hostname }}.txt"
